// <auto-generated />
using System;
using AigoraNet.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AigoraNet.Common.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20251229223136_AddTokenPromptMapping")]
    partial class AddTokenPromptMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AigoraNet.Common.BoardCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("BoardMasterId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BoardCategories");
                });

            modelBuilder.Entity("AigoraNet.Common.BoardContent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnwerOwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MasterId");

                    b.ToTable("BoardContents");
                });

            modelBuilder.Entity("AigoraNet.Common.BoardMaster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<byte>("BoardType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MasterCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MasterCode")
                        .IsUnique();

                    b.ToTable("BoardMasters");
                });

            modelBuilder.Entity("AigoraNet.Common.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("ParentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AigoraNet.Common.CommentHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<byte>("HistoryType")
                        .HasColumnType("tinyint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RegistDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("CommentId", "OwnerId")
                        .IsUnique();

                    b.ToTable("CommentHistory");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.FileMaster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("FileBlob")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("FileLength")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PublicURL")
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("RegistDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileMasters");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.KeywordPrompt", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsRegex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PromptTemplateId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("Keyword", "Locale")
                        .IsUnique()
                        .HasFilter("[Locale] IS NOT NULL");

                    b.ToTable("KeywordPrompts");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.LogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LogEvent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.Member", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EmailConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmailConfirm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)10);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.PromptTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version", "Locale")
                        .IsUnique()
                        .HasFilter("[Locale] IS NOT NULL");

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.Token", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TokenKey")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.TokenPromptMapping", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PromptTemplateId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("TokenId", "PromptTemplateId")
                        .IsUnique();

                    b.ToTable("TokenPromptMappings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("AigoraNet.Common.BoardContent", b =>
                {
                    b.HasOne("AigoraNet.Common.BoardCategory", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AigoraNet.Common.BoardMaster", "Master")
                        .WithMany("Contents")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("BoardContentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BoardContentId");

                            b1.ToTable("BoardContents");

                            b1.WithOwner()
                                .HasForeignKey("BoardContentId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("AigoraNet.Common.BoardMaster", b =>
                {
                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("BoardMasterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BoardMasterId");

                            b1.ToTable("BoardMasters");

                            b1.WithOwner()
                                .HasForeignKey("BoardMasterId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();
                });

            modelBuilder.Entity("AigoraNet.Common.Comment", b =>
                {
                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("CommentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CommentId");

                            b1.ToTable("Comments");

                            b1.WithOwner()
                                .HasForeignKey("CommentId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();
                });

            modelBuilder.Entity("AigoraNet.Common.CommentHistory", b =>
                {
                    b.HasOne("AigoraNet.Common.Comment", "Comment")
                        .WithMany("Historian")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.FileMaster", b =>
                {
                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("FileMasterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FileMasterId");

                            b1.ToTable("FileMasters");

                            b1.WithOwner()
                                .HasForeignKey("FileMasterId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.KeywordPrompt", b =>
                {
                    b.HasOne("AigoraNet.Common.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany("KeywordPrompts")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("KeywordPromptId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("KeywordPromptId");

                            b1.ToTable("KeywordPrompts");

                            b1.WithOwner()
                                .HasForeignKey("KeywordPromptId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("PromptTemplate");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.Member", b =>
                {
                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("MemberId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MemberId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.PromptTemplate", b =>
                {
                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("PromptTemplateId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PromptTemplateId");

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.Token", b =>
                {
                    b.HasOne("AigoraNet.Common.Entities.Member", "Member")
                        .WithMany("Tokens")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("TokenId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TokenId");

                            b1.ToTable("Tokens");

                            b1.WithOwner()
                                .HasForeignKey("TokenId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.TokenPromptMapping", b =>
                {
                    b.HasOne("AigoraNet.Common.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany()
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AigoraNet.Common.Entities.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AigoraNet.Common.AuditableEntity", "Condition", b1 =>
                        {
                            b1.Property<string>("TokenPromptMappingId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeletedDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUpdate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<DateTime>("RegistDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasDefaultValueSql("getutcdate()");

                            b1.Property<byte>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint")
                                .HasDefaultValue((byte)1);

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TokenPromptMappingId");

                            b1.ToTable("TokenPromptMappings");

                            b1.WithOwner()
                                .HasForeignKey("TokenPromptMappingId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("PromptTemplate");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("AigoraNet.Common.BoardCategory", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("AigoraNet.Common.BoardMaster", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("AigoraNet.Common.Comment", b =>
                {
                    b.Navigation("Historian");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.Member", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("AigoraNet.Common.Entities.PromptTemplate", b =>
                {
                    b.Navigation("KeywordPrompts");
                });
#pragma warning restore 612, 618
        }
    }
}
